#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : django_openstack_auth
Version  : 2.4.1
Release  : 32
URL      : http://tarballs.openstack.org/django_openstack_auth/django_openstack_auth-2.4.1.tar.gz
Source0  : http://tarballs.openstack.org/django_openstack_auth/django_openstack_auth-2.4.1.tar.gz
Source99 : http://tarballs.openstack.org/django_openstack_auth/django_openstack_auth-2.4.1.tar.gz.asc
Summary  : Django authentication backend for use with OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: django_openstack_auth-python
Requires: Django
Requires: keystoneauth1
Requires: oslo.config
Requires: oslo.policy
Requires: pbr
Requires: python-keystoneclient
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=====================
Django OpenStack Auth
=====================
Django OpenStack Auth is a pluggable Django authentication backend that
works with Django's ``contrib.auth`` framework to authenticate a user against
OpenStack's Keystone Identity API.

%package python
Summary: python components for the django_openstack_auth package.
Group: Default

%description python
python components for the django_openstack_auth package.


%prep
%setup -q -n django_openstack_auth-2.4.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489274307
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489274307
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
